// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDrQeDCwv78a0wqx3UyDc4sWS749R8LkE',
    appId: '1:519958265576:web:7c7ee42d08b887a359135d',
    messagingSenderId: '519958265576',
    projectId: 'aqms-1d833',
    authDomain: 'aqms-1d833.firebaseapp.com',
    databaseURL: 'https://aqms-1d833-default-rtdb.firebaseio.com',
    storageBucket: 'aqms-1d833.firebasestorage.app',
    measurementId: 'G-SG9G9X6KVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTg0XDdLbxX5ZGlsi8YvXPyX1-1vr_pV4',
    appId: '1:519958265576:android:7e9c6275702bfb1859135d',
    messagingSenderId: '519958265576',
    projectId: 'aqms-1d833',
    databaseURL: 'https://aqms-1d833-default-rtdb.firebaseio.com',
    storageBucket: 'aqms-1d833.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDrQeDCwv78a0wqx3UyDc4sWS749R8LkE',
    appId: '1:519958265576:web:d9295dffb299d45c59135d',
    messagingSenderId: '519958265576',
    projectId: 'aqms-1d833',
    authDomain: 'aqms-1d833.firebaseapp.com',
    databaseURL: 'https://aqms-1d833-default-rtdb.firebaseio.com',
    storageBucket: 'aqms-1d833.firebasestorage.app',
    measurementId: 'G-FWRC44TJ4X',
  );
}
